### ISSUE TITLE
Could not find generator 'talking_stick:views

### ISSUE THREAD

**Issue by breim** [mojolingo/talking_stick#17]
Log
Rails 4.2.3 and ruby 2.2.2

[vagrant|4.2.3#2.2.2] /Projects/calling
$ rails g talking_stick:views
Could not find generator 'talking_stick:views'. Maybe you meant 'assets', 'integration_test' or 'migration'
Run `rails generate --help` for more options.

**Comment by bklang** [comment]
It sounds like you may not have the Engine loaded? This generator is working fine for me:

```
$ rails generate talking_stick:views
      create  app/views/talking_stick/participants
      create  app/views/talking_stick/participants/_form.html.erb
      create  app/views/talking_stick/participants/edit.html.erb
      create  app/views/talking_stick/participants/index.html.erb
      create  app/views/talking_stick/participants/new.html.erb
      create  app/views/talking_stick/participants/show.html.erb
       exist  app/views/talking_stick/rooms
      create  app/views/talking_stick/rooms/_form.html.erb
      create  app/views/talking_stick/rooms/edit.html.erb
      create  app/views/talking_stick/rooms/index.html.erb
      create  app/views/talking_stick/rooms/new.html.erb
# snip more files
```

Please post your Gemfile

**Comment by breim** [comment]
Fast answer! Thx buddy!
I solve this running bundle exec spring binstub --all

I think it's something on my machine, you can close this issue.
Sorry for taking your time

LOG:
[vagrant|4.2.3#2.2.2] /Projects/call
$ bundle exec spring binstub --all
- bin/rake: spring already present
- bin/rails: spring already present

[vagrant|4.2.3#2.2.2] /Projects/call
$ rails generate talking_stick:views
      create  app/views/talking_stick/participants
      create  app/views/talking_stick/participants/_form.html.erb
      create  app/views/talking_stick/participants/edit.html.erb
      create  app/views/talking_stick/participants/index.html.erb
      create  app/views/talking_stick/participants/new.html.erb
      create  app/views/talking_stick/participants/show.html.erb
      create  app/views/talking_stick/rooms
      create  app/views/talking_stick/rooms/_form.html.erb
      create  app/views/talking_stick/rooms/edit.html.erb
      create  app/views/talking_stick/rooms/index.html.erb
      create  app/views/talking_stick/rooms/new.html.erb
      create  app/views/talking_stick/rooms/show.html.erb
