### ISSUE TITLE
WebRTC one to many

### ISSUE THREAD

**Issue by danieldocki** [mojolingo/talking_stick#19]
Today do not have any option that can be made a livestream? A transmission from one to several?

Thanks for the lib

**Comment by bklang** [comment]
WebRTC can be used for broadcasting, but you should carefully consider what you're trying to accomplish. If you simply want video broadcasting, there are better tools for the job.  Also, depending on the number of connections you need to support, you may also need some kind of SFU or MCU. Check out [Jitsi Videobridge](https://jitsi.org/Projects/JitsiVideobridge) or [Kurento Media Server](http://www.kurento.org/)

If you have more specific questions about TalkingStick, let me know.

**Comment by danieldocki** [comment]
@bklang Thanks for your attention and your indications.
