### ISSUE TITLE
Helpers and routes not being detected in the talking_stick views

### ISSUE THREAD

**Issue by suramai** [mojolingo/talking_stick#22]
Hello,

Could you please share how I can access the helpers and routes inside the talking stick views?

```
Started GET "/talking_stick/rooms" for 142.105.174.115 at 2016-01-17 01:26:23 +0000
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by TalkingStick::RoomsController#index as HTML
  TalkingStick::Room Load (0.4ms)  SELECT "talking_stick_rooms".* FROM "talking_stick_rooms"
  Rendered talking_stick/rooms/index.html.erb within layouts/application (53.3ms)
Completed 500 Internal Server Error in 554ms (ActiveRecord: 1.3ms)

NoMethodError (undefined method `full_title' for #<#<Class:0x00000008c82668>:0x00000008c75508>):
  app/views/layouts/application.html.erb:22:in `_app_views_layouts_application_html_erb___4228776872201960948_73395740'
```

It works if I removes all the helpers and path variables from the navbar, footer and application layout.

**Comment by bklang** [comment]
This isn't something specific to Talking Stick, but comes from the fact that Talking Stick is delivered as a Rails Engine. Check out this link and see if it helps: http://stackoverflow.com/questions/8028021/helpers-in-rails-engine

**Comment by suramai** [comment]
Oh I am sorry. I am a newbie. Thank you for sharing the link and prompt response @bklang
I will check it.

**Comment by suramai** [comment]
I couldn't get it working. Kindly share instructions if you have @bklang 
I checked the source code of the demo app to get some idea. I think it works because you don't have helpers and routes there.
