### ISSUE TITLE
Rails 5.0 Support

### ISSUE THREAD

**Issue by etagwerker** [mojolingo/talking_stick#35]
Hi,

I think it'd be great if `talking_stick` was compatible with Rails 5.0

Right now I see that this is the version requirement:

```
talking_stick depends on rails (< 5.0, > 3.0)
```

Ernesto

**Comment by lpradovera** [comment]
Hello,
there is a `feature/rails-5` branch I am actively working on because I need it for a project.
Feel free to check it out and maybe help me test it!
Thanks!

**Comment by etagwerker** [comment]
@lpradovera Awesome! I'll check it out. What's the status of that branch?

**Comment by etagwerker** [comment]
@lpradovera I managed to get the spec to pass with its existing scenarios. It's in PR https://github.com/mojolingo/talking_stick/pull/36

What other tests can we add?

**Comment by bklang** [comment]
Closing in favor of #38
