### ISSUE TITLE
How can I subscribe sound only?

### ISSUE THREAD

**Issue by Uysim** [mojolingo/talking_stick#42]
Is there a way to subscribe sound only without video?

**Comment by victorhazbun** [comment]
is this repo alive?

**Comment by lpradovera** [comment]
I guess that if you have to ask a question, you can ask it, @victorhazbun :)

**Comment by nikolabjelo** [comment]
So let's ask it : Is there a way to subscribe sound only without video?

**Comment by bklang** [comment]
Have a look at the [options passed into the TalkingStick JS object](https://github.com/mojolingo/talking_stick/blob/develop/app/assets/javascripts/talking_stick/talking_stick.js.erb#L8).  There are several things you can control, which include whether to activate audio or video.  Note that the `audio` and `video` options there are for determining whether to request the user to provide access to the local camera and microphone. That means these options control *sending* media, not receiving.

If you want to only playback audio and hide the video, you can always style the `<video>` tag to `display: false`.  Does that work for your use-case?

**Comment by nikolabjelo** [comment]
Working with the options from the TalkingStick JS Object did the trick. Thanks
